<?php

return [
    /**
     * Only update when working on the EnvX base.
     */
    'version' => '2020-11-24',

    /**
     * Vapor/AWS:
     */
    's3-asset-path' => 'https://asset-url.cloudfront.net/',

    /**
     * Virtual Product Type
     *
     * Application manipulation set in the ProductServiceProvider
     * !!! When changing product types or additional modules you must run "php artisan envx:cache:modules"
     *
     * OPTIONS:
     * 'broadcast'  | The virtual broadcast product
     * 'experience' | The virtual experience product
     */
    'product-type' => env('ENVX_PRODUCT_TYPE', 'broadcast'),
    'additional-modules' => [
        //         'social',
        //         'wordclouds',
        //         'breakout-rooms',
    ],

    /**
     * Authentication settings
     *
     * Container resolution located in the AuthServiceProvider.
     * !!! Certain product-type SP's will override the 'auth-handler.type' value
     * !!! Certain auth handlers will override the 'auth-handler.creates' value
     *
     * TYPE:
     * 'email'                      | Log the user in by email.
     * 'email-whitelist             | Log the user in by email, adheres to whitelist.
     * 'password'                   | Log the user in with their password. (Assumes sending invite emails.)
     * 'password-generic'           | Log the user in with a generic password.
     * 'password-generic-whitelist' | Log the user in with a generic password, adheres to whitelist.
     *
     * CREATES:
     * 'true'  | The handler will create a user if a record is not found and the handler allows it.
     * 'false' | The handler will NOT create a user if a record is not found.
     *
     */
    'auth-handler' => [
        'type' => env('ENVX_AUTH_HANDLER', 'password'),
        'creates' => true,
        'whitelist' => [
            '@drpgroup'
        ],
    ],
    'recaptcha' => false,
    'block-concurrent-logins' => env('BLOCK_CONCURRENT_LOGINS', false),

    'generic-password' => env('ENVX_USER_GENERIC_PASSWORD', 'Transform2021!'),

    'temp-password' => env('ENVX_USER_TEMP_PASSWORD', 'Transform2021!'),
    'temp-password-admin' => env('ENVX_ADMIN_TEMP_PASSWORD', 'Transform2021!'),

    /*
     * Event Settings
     *
     * !!! Use EventInfo facade to access.
     *
     * Keys can be accessed with magic methods:
     * EventInfo::client()
     * EventInfo::clientLogo()
     *
     * Nested keys can be accessed through a parameter:
     * EventInfo::contact('email')
     * EventInfo::contact('example.key')
     *
     * Date/Time formatting classes can be accessed with:
     * EventInfo::date() - returns EventDateFormatter class
     * EventInfo::time() - returns EventTimeFormatter class
     *
     * Both have access to a full() method for entire date/time
     * Both have access to startRaw()/endRaw() which returns the carbon instance
     * EventInfo::date()->full()
     * EventInfo::time()->startRaw()
     *
     * You may also affix Formatter methods to the Date/Time methods:
     * EventInfo::dateStart() becomes EventInfo::date()->start()
     *
     * Multi-day info handler can be accessed with:
     * EventInfo::dates() - returns EventDatesHandler class
     *
     * Available methods:
     * EventInfo::dates()->count() - total day count
     * EventInfo::dates()->current() - current day number
     * EventInfo::dates()->currentRaw() - current day carbon instance
     *
     * You may also affix handler methods to the Dates method:
     * EventInfo::datesCount() becomes EventInfo::dates()->count()
     */
    'event' => [
        'client' => 'Hyster-Yale',
        'client-logo' => 'img/logos/drpg-logo-white.png',
        'client-logo-inverse' => 'img/logos/drpg-logo-black.png',

        'title' => 'Transform',

        'start' => isYale() ? '2021-04-14 12:30' : '2021-04-14 08:30',
        'end' => isYale() ? '2021-04-14 14:00' : '2021-04-14 11:30',

        'contact' => [
            'email' => 'example@drpgroup.com',
            'phone' => '1234567890',
        ],

        'privacy-policy' => 'https://www.drpgroup.com/hubfs/DRPG/Policies/DRPG%20Cookie%20%26%20Privacy%20Policy.pdf?hsLang=en',
    ],

    /**
     * Emails
     *
     * Defines mailables that can be bulk sent
     * A static recipients() method must exist on the class
     */
    'emails' => [
        'apology' => \App\Mail\ApologyEmail::class,
        'invite-yale' => \App\Mail\Yale\Invite::class,
        'invite-hyster' => \App\Mail\Hyster\Invite::class,
        'reminder-yale' => \App\Mail\Reminder::class,
        'reminder-hyster' => \App\Mail\Reminder::class,
        'save-the-date-hyster' => \App\Mail\Hyster\SaveTheDate::class,
        'save-the-date-yale' => \App\Mail\Yale\SaveTheDate::class
    ],

    /**
     * Application defaults
     */
    'queues' => [
        'emails' => env('ENVX_QUEUE_NAME_EMAILS'),
        'analytics' => env('ENVX_QUEUE_NAME_ANALYTICS'),
        'notifications' => env('ENVX_QUEUE_NAME_NOTIFICATIONS'),
    ],

    'forms' => [
        'labelWidth' => 4,
        'inputWidth' => 6,
        'horizontal' => false,
    ],

    'teaser-videos' => [
        'hyster' => [
            'cs' => [
                'video_name' => 'Hyster Teaser - Czech Translation',
                'vimeo_link' => 'https://vimeo.com/491143333/d628e7d5ee',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491143333" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'nl' => [
                'video_name' => 'Hyster Teaser -Dutch Translation',
                'vimeo_link' => 'https://vimeo.com/491608401/92da714ba8',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491608401" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'en' => [
                'video_name' => 'Hyster Teaser - English Translation',
                'vimeo_link' => 'https://vimeo.com/491610395/7155d92446',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491610395" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'fr' => [
                'video_name' => 'Hyster Teaser - French Translation',
                'vimeo_link' => 'https://vimeo.com/491611377/feb7e45c4a',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491611377" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'de' => [
                'video_name' => 'Hyster Teaser - German Translation',
                'vimeo_link' => 'https://vimeo.com/491612799/aee282f188',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491612799" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'it' => [
                'video_name' => 'Hyster Teaser - Italian Translation',
                'vimeo_link' => 'https://vimeo.com/491613657/cc052e57c9',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491613657" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'pl' => [
                'video_name' => 'Hyster Teaser - Polish Translation',
                'vimeo_link' => 'https://vimeo.com/491614331/b4e43a89fb',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491614331" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'ru' => [
                'video_name' => 'Hyster Teaser - Russian Translation',
                'vimeo_link' => 'https://vimeo.com/491632323/ecf6a961a0',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491632323" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'es' => [
                'video_name' => 'Hyster Teaser - Spanish Translation',
                'vimeo_link' => 'https://vimeo.com/491633774/c851311f5f',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491633774" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
        ],
        'yale' => [
            'cs' => [
                'video_name' => 'Yale Teaser - Czech Translation',
                'vimeo_link' => 'https://vimeo.com/491694489/195c99d512',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491694489" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'nl' => [
                'video_name' => 'Yale Teaser -Dutch Translation',
                'vimeo_link' => 'https://vimeo.com/491694642/35cf3d33fd',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491694642" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'en' => [
                'video_name' => 'Yale Teaser - English Translation',
                'vimeo_link' => 'https://vimeo.com/491694781/fc3f0b9967',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491694781" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'fr' => [
                'video_name' => 'Yale Teaser - French Translation',
                'vimeo_link' => 'https://vimeo.com/491694978/aedeadf0fd',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491694978" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'de' => [
                'video_name' => 'Yale Teaser - German Translation',
                'vimeo_link' => 'https://vimeo.com/491695098/833e391149',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491695098" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'it' => [
                'video_name' => 'Yale Teaser - Italian Translation',
                'vimeo_link' => 'https://vimeo.com/491695259/ba61522d6f',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491695259" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'pl' => [
                'video_name' => 'Yale Teaser - Polish Translation',
                'vimeo_link' => 'https://vimeo.com/491695456/3e79d945ec',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491695456" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'ru' => [
                'video_name' => 'Yale Teaser - Russian Translation',
                'vimeo_link' => 'https://vimeo.com/491695613/10d6c4b55d',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491695613" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
            'es' => [
                'video_name' => 'Yale Teaser - Spanish Translation',
                'vimeo_link' => 'https://vimeo.com/491695863/196ca61ce0',
                'vimeo_iframe' => '<iframe src="https://player.vimeo.com/video/491695863" width="640" height="361" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>',
            ],
        ],
    ],

    'countries' => [
        'en' => [
            "Afghanistan" => "Afghanistan",
            "Albania" => "Albania",
            "Algeria" => "Algeria",
            "Andorra" => "Andorra",
            "Angola" => "Angola",
            "Antigua and Barbuda" => "Antigua and Barbuda",
            "Argentina" => "Argentina",
            "Armenia" => "Armenia",
            "Australia" => "Australia",
            "Austria" => "Austria",
            "Azerbaijan" => "Azerbaijan",
            "Bahamas" => "Bahamas",
            "Bahrain" => "Bahrain",
            "Bangladesh" => "Bangladesh",
            "Barbados" => "Barbados",
            "Belarus" => "Belarus",
            "Belgium" => "Belgium",
            "Belize" => "Belize",
            "Benin" => "Benin",
            "Bhutan" => "Bhutan",
            "Bolivia" => "Bolivia",
            "Bosnia and Herzegovina" => "Bosnia and Herzegovina",
            "Botswana" => "Botswana",
            "Brazil" => "Brazil",
            "Brunei" => "Brunei",
            "Bulgaria" => "Bulgaria",
            "Burkina Faso" => "Burkina Faso",
            "Burundi" => "Burundi",
            "Côte d'Ivoire" => "Côte d'Ivoire",
            "Cabo Verde" => "Cabo Verde",
            "Cambodia" => "Cambodia",
            "Cameroon" => "Cameroon",
            "Canada" => "Canada",
            "Central African Republic" => "Central African Republic",
            "Chad" => "Chad",
            "Chile" => "Chile",
            "China" => "China",
            "Colombia" => "Colombia",
            "Comoros" => "Comoros",
            "Congo (Congo-Brazzaville)" => "Congo (Congo-Brazzaville)",
            "Costa Rica" => "Costa Rica",
            "Croatia" => "Croatia",
            "Cuba" => "Cuba",
            "Cyprus" => "Cyprus",
            "Czechia (Czech Republic)" => "Czechia (Czech Republic)",
            "Democratic Republic of the Congo", "Democratic Republic of the Congo",
            "Denmark" => "Denmark",
            "Djibouti" => "Djibouti",
            "Dominica" => "Dominica",
            "Dominican Republic" => "Dominican Republic",
            "Ecuador" => "Ecuador",
            "Egypt" => "Egypt",
            "El Salvador" => "El Salvador",
            "Equatorial Guinea" => "Equatorial Guinea",
            "Eritrea" => "Eritrea",
            "Estonia" => "Estonia",
            "Eswatini" => "Eswatini",
            "Ethiopia" => "Ethiopia",
            "Fiji" => "Fiji",
            "Finland" => "Finland",
            "France" => "France",
            "Gabon" => "Gabon",
            "Gambia" => "Gambia",
            "Georgia" => "Georgia",
            "Germany" => "Germany",
            "Ghana" => "Ghana",
            "Greece" => "Greece",
            "Grenada" => "Grenada",
            "Guatemala" => "Guatemala",
            "Guinea" => "Guinea",
            "Guinea-Bissau" => "Guinea-Bissau",
            "Guyana" => "Guyana",
            "Haiti" => "Haiti",
            "Holy See" => "Holy See",
            "Honduras" => "Honduras",
            "Hungary" => "Hungary",
            "Iceland" => "Iceland",
            "India" => "India",
            "Indonesia" => "Indonesia",
            "Iran" => "Iran",
            "Iraq" => "Iraq",
            "Ireland" => "Ireland",
            "Israel" => "Israel",
            "Italy" => "Italy",
            "Jamaica" => "Jamaica",
            "Japan" => "Japan",
            "Jordan" => "Jordan",
            "Kazakhstan" => "Kazakhstan",
            "Kenya" => "Kenya",
            "Kiribati" => "Kiribati",
            "Kuwait" => "Kuwait",
            "Kyrgyzstan" => "Kyrgyzstan",
            "Laos" => "Laos",
            "Latvia" => "Latvia",
            "Lebanon" => "Lebanon",
            "Lesotho" => "Lesotho",
            "Liberia" => "Liberia",
            "Libya" => "Libya",
            "Liechtenstein" => "Liechtenstein",
            "Lithuania" => "Lithuania",
            "Luxembourg" => "Luxembourg",
            "Madagascar" => "Madagascar",
            "Malawi" => "Malawi",
            "Malaysia" => "Malaysia",
            "Maldives" => "Maldives",
            "Mali" => "Mali",
            "Malta" => "Malta",
            "Marshall Islands" => "Marshall Islands",
            "Mauritania" => "Mauritania",
            "Mauritius" => "Mauritius",
            "Mexico" => "Mexico",
            "Micronesia" => "Micronesia",
            "Moldova" => "Moldova",
            "Monaco" => "Monaco",
            "Mongolia" => "Mongolia",
            "Montenegro" => "Montenegro",
            "Morocco" => "Morocco",
            "Mozambique" => "Mozambique",
            "Myanmar" => "Myanmar",
            "Namibia" => "Namibia",
            "Nauru" => "Nauru",
            "Nepal" => "Nepal",
            "Netherlands" => "Netherlands",
            "New Zealand" => "New Zealand",
            "Nicaragua" => "Nicaragua",
            "Niger" => "Niger",
            "Nigeria" => "Nigeria",
            "North Korea" => "North Korea",
            "North Macedonia" => "North Macedonia",
            "Norway" => "Norway",
            "Oman" => "Oman",
            "Pakistan" => "Pakistan",
            "Palau" => "Palau",
            "Palestine State" => "Palestine State",
            "Panama" => "Panama",
            "Papua New Guinea" => "Papua New Guinea",
            "Paraguay" => "Paraguay",
            "Peru" => "Peru",
            "Philippines" => "Philippines",
            "Poland" => "Poland",
            "Portugal" => "Portugal",
            "Qatar","Qatar",
            "Romania" => "Romania",
            "Russia" => "Russia",
            "Rwanda" => "Rwanda",
            "Saint Kitts and Nevis" => "Saint Kitts and Nevis",
            "Saint Lucia" => "Saint Lucia",
            "Saint Vincent and the Grenadines" => "Saint Vincent and the Grenadines",
            "Samoa" => "Samoa",
            "San Marino" => "San Marino",
            "Sao Tome and Principe" => "Sao Tome and Principe",
            "Saudi Arabia" => "Saudi Arabia",
            "Senegal" => "Senegal",
            "Serbia" => "Serbia",
            "Seychelles" => "Seychelles",
            "Sierra Leone" => "Sierra Leone",
            "Singapore" => "Singapore",
            "Slovakia" => "Slovakia",
            "Slovenia" => "Slovenia",
            "Solomon Islands" => "Solomon Islands",
            "Somalia" => "Somalia",
            "South Africa" => "South Africa",
            "South Korea" => "South Korea",
            "South Sudan" => "South Sudan",
            "Spain" => "Spain",
            "Sri Lanka" => "Sri Lanka",
            "Sudan" => "Sudan",
            "Suriname" => "Suriname",
            "Sweden" => "Sweden",
            "Switzerland" => "Switzerland",
            "Syria" => "Syria",
            "Tajikistan" => "Tajikistan",
            "Tanzania" => "Tanzania",
            "Thailand" => "Thailand",
            "Timor-Leste" => "Timor-Leste",
            "Togo" => "Togo",
            "Tonga" => "Tonga",
            "Trinidad and Tobago" => "Trinidad and Tobago",
            "Tunisia" => "Tunisia",
            "Turkey" => "Turkey",
            "Turkmenistan" => "Turkmenistan",
            "Tuvalu" => "Tuvalu",
            "Uganda" => "Uganda",
            "Ukraine" => "Ukraine",
            "United Arab Emirates" => "United Arab Emirates",
            "United Kingdom" => "United Kingdom",
            "United States of America" => "United States of America",
            "Uruguay" => "Uruguay",
            "Uzbekistan" => "Uzbekistan",
            "Vanuatu" => "Vanuatu",
            "Venezuela" => "Venezuela",
            "Vietnam" => "Vietnam",
            "Yemen" => "Yemen",
            "Zambia" => "Zambia",
            "Zimbabwe" => "Zimbabwe",
        ],
        'de' => [
            "Afghanistan" => "Afghanistan",
            "Albanien" => "Albanien",
            'Algerien' => 'Algerien',
            'Andorra' => 'Andorra',
            'Angola' => 'Angola',
            'Antigua und Barbuda' => 'Antigua und Barbuda',
            'Argentinien' => 'Argentinien',
            'Armenien' => 'Armenien',
            'Australien' => 'Armenien',
            'Österreich' => 'Österreich',
            'Aserbaidschan' => 'Aserbaidschan',
            'Bahamas' => 'Bahamas',
            'Bahrain' => 'Bahrain',
            'Bangladesch' => 'Bangladesch',
            'Barbados' => 'Barbados',
            'Weißrussland' => 'Weißrussland',
            'Belgien' => 'Belgien',
            'Belize' => 'Belize',
            'Benin' => 'Benin',
            'Bhutan' => 'Bhutan',
            'Bolivien' => 'Bolivien',
            'Bosnien und Herzegowina' => 'Bosnien und Herzegowina',
            'Botswana' => 'Botswana',
            'Brasilien' => 'Brasilien',
            'Brunei' => 'Brunei',
            'Bulgarien' => 'Bulgarien',
            'Burkina Faso' => 'Burkina Faso',
            'Burundi' => 'Burundi',
            "Côte d'Ivoire" => "Côte d'Ivoire",
            "Cabo Verde" => 'Cabo Verde',
            'Kambodscha' => 'Kambodscha',
            'Kamerun' => 'Kamerun',
            'Kanada' => 'Kanada',
            "Zentralafrikanische Republik" => "Zentralafrikanische Republik",
            'Tschad' => 'Tschad',
            'Chile' => 'Chile',
            'China' => 'China',
            'Kolumbien' => 'Kolumbien',
            'Komoren' => 'Komoren',
            'Kongo (Kongo-Brazzaville)' => 'Kongo (Kongo-Brazzaville)',
            'Costa Rica' => 'Costa Rica',
            'Kroatien' => 'Kroatien',
            'Kuba' => 'Kuba',
            'Zypern' => 'Zypern',
            "Tschechien (Tschechische Republik)" => "Tschechien (Tschechische Republik)",
            'Demokratische Republik Kongo' => 'Demokratische Republik Kongo',
            'Dänemark' => 'Dänemark',
            'Dschibuti' => 'Dschibuti',
            'Dominica' => 'Dominica',
            'Dominikanische Republik' => 'Dominikanische Republik',
            'Ecuador' => 'Ecuador',
            'Ägypten' => 'Ägypten',
            'El Salvador' => 'El Salvador',
            'Äquatorial-Guinea' => 'Äquatorial-Guinea',
            'Eritrea' => 'Eritrea',
            'Estland' => 'Estland',
            'Eswatini' => 'Eswatini',
            'Äthiopien' => 'Äthiopien',
            'Fidschi' => 'Fidschi',
            'Finnland' => 'Finnland',
            'Frankreich' => 'Frankreich',
            'Gabun' => 'Gabun',
            'Gambia' => 'Gambia',
            'Georgien' => 'Georgien',
            'Deutschland' => 'Deutschland',
            'Ghana' => 'Ghana',
            'Griechenland' => 'Griechenland',
            'Grenada' => 'Grenada',
            'Guatemala' => 'Guatemala',
            'Guinea' => 'Guinea',
            'Guinea-Bissau' => 'Guinea-Bissau',
            'Guyana' => 'Guyana',
            'Haiti' => 'Haiti',
            'Heiliger Stuhl' => 'Heiliger Stuhl',
            'Honduras' => 'Honduras',
            'Ungarn' => 'Ungarn',
            'Island' => 'Island',
            'Indien' => 'Indien',
            'Indonesien' => 'Indonesien',
            'Iran' => 'Iran',
            'Irak' => 'Irak',
            'Irland' => 'Irland',
            'Israel' => 'Israel',
            'Italien' => 'Italien',
            'Jamaika' => 'Jamaika',
            'Japan' => 'Japan',
            'Jordanien' => 'Jordanien',
            'Kasachstan' => 'Kasachstan',
            'Kenia' => 'Kenia',
            'Kiribati' => 'Kiribati',
            'Kuwait' => 'Kuwait',
            'Kirgisistan' => 'Kirgisistan',
            'Laos' => 'Laos',
            'Lettland' => 'Lettland',
            'Libanon' => 'Libanon',
            'Lesotho' => 'Lesotho',
            'Liberia' => 'Liberia',
            'Libyen' => 'Libyen',
            'Liechtenstein' => 'Liechtenstein',
            'Litauen' => 'Litauen',
            'Luxemburg' => 'Luxemburg',
            'Madagaskar' => 'Madagaskar',
            'Malawi' => 'Malawi',
            'Malaysia' => 'Malaysia',
            'Malediven' => 'Malediven',
            'Mali' => 'Mali',
            'Malta' => 'Malta',
            'Marshall-Inseln' => 'Marshall-Inseln',
            'Mauretanien' => 'Mauretanien',
            'Mauritius' => 'Mauritius',
            'Mexiko' => 'Mexiko',
            'Mikronesien' => 'Mikronesien',
            'Moldawien' => 'Moldawien',
            'Monaco' => 'Monaco',
            'Mongolei' => 'Mongolei',
            'Montenegro' => 'Montenegro',
            'Marokko' => 'Marokko',
            'Mosambik' => 'Mosambik',
            'Myanmar' => 'Myanmar',
            'Namibia' => 'Namibia',
            'Nauru' => 'Nauru',
            'Nepal' => 'Nepal',
            'Niederlande' => 'Niederlande',
            'neuseeland' => 'neuseeland',
            'Nicaragua' => 'Nicaragua',
            'Niger' => 'Niger',
            'Nigeria' => 'Nigeria',
            'Nordkorea' => 'Nordkorea',
            'Nord-Mazedonien' => 'Nord-Mazedonien',
            'Norwegen' => 'Norwegen',
            'Oman' => 'Oman',
            'Pakistan' => 'Pakistan',
            'Palau' => 'Palau',
            'Palästina Staat' => 'Palästina Staat',
            'Panama' => 'Panama',
            'Papua-Neuguinea' => 'Papua-Neuguinea',
            'Paraguay' => 'Paraguay',
            'Peru' => 'Peru',
            'Philippinen' => 'Philippinen',
            'Polen' => 'Polen',
            'Portugal' => 'Portugal',
            'Katar' => 'Katar',
            'Rumänien' => 'Rumänien',
            'Russland' => 'Russland',
            'Ruanda' => 'Ruanda',
            'St. Kitts und Nevis' => 'St. Kitts und Nevis',
            'St. Lucia' => 'St. Lucia',
            'St. Vincent und die Grenadinen' => 'St. Vincent und die Grenadinen',
            'Samoa' => 'Samoa',
            'San Marino' => 'San Marino',
            'Sao Tome und Principe' => 'Sao Tome und Principe',
            'Saudi-Arabien' => 'Saudi-Arabien',
            'Senegal' => 'Senegal',
            'Serbien' => 'Serbien',
            'Seychellen' => 'Seychellen',
            'Sierra Leone' => 'Sierra Leone',
            'Singapur' => 'Singapur',
            'Slowakei' => 'Slowakei',
            'Slowenien' => 'Slowenien',
            'Salomon-Inseln' => 'Salomon-Inseln',
            'Somalia' => 'Somalia',
            'Süd-Afrika' => 'Süd-Afrika',
            'Südkorea' => 'Südkorea',
            'Südsudan' => 'Südsudan',
            'Spanien' => 'Spanien',
            'Sri Lanka' => 'Sri Lanka',
            'Sudan' => 'Sudan',
            'Surinam' => 'Surinam',
            'Schweden' => 'Schweden',
            'Schweiz' => 'Schweiz',
            'Syrien' => 'Syrien',
            'Tadschikistan' => 'Tadschikistan',
            'Tansania' => 'Tansania',
            'Thailand' => 'Thailand',
            'Timor-Leste' => 'Timor-Leste',
            'Togo' => 'Togo',
            'Tonga' => 'Tonga',
            'Trinidad und Tobago' => 'Trinidad und Tobago',
            'Tunesien' => 'Tunesien',
            'Türkei' => 'Türkei',
            'Turkmenistan' => 'Turkmenistan',
            'Tuvalu' => 'Tuvalu',
            'Uganda' => 'Uganda',
            'Ukraine' => 'Ukraine',
            'Vereinigte Arabische Emirate' => 'Vereinigte Arabische Emirate',
            'Vereinigtes Königreich' => 'Vereinigtes Königreich',
            'Vereinigte Staaten von Amerika' => 'Vereinigte Staaten von Amerika',
            'Uruguay' => 'Uruguay',
            'Usbekistan' => 'Usbekistan',
            'Vanuatu' => 'Vanuatu',
            'Venezuela' => 'Venezuela',
            'Vietnam' => 'Vietnam',
            'Jemen' => 'Jemen',
            'Sambia' => 'Sambia',
            'Simbabwe' => 'Simbabwe'
        ],
        'nl' => [
            "Afghanistan" => "Afghanistan",
            "Albanië" => "Albanië",
            "Algerije" => "Algerije",
            "Andorra" => "Andorra",
            "Angola" => "Angola",
          "Antigua en Barbuda" => "Antigua en Barbuda",
          "Argentinië" => "Argentinië",
          "Armenië" => "Armenië",
          "Australië" => "Australië",
          "Oostenrijk" => "Oostenrijk",
          "Azerbeidzjan" => "Azerbeidzjan",
          "Bahama's" => "Bahama's",
          "Bahrein" => "Bahrein",
          "Bangladesh" => "Bangladesh",
          "Barbados" => "Barbados",
          "Wit-Rusland" => "Wit-Rusland",
          "België" => "België",
          "Belize" => "Belize",
          "Benin" => "Benin",
          "Bhutan" => "Bhutan",
          "Bolivia" => "Bolivia",
          "Bosnië en Herzegovina" => "Bosnië en Herzegovina",
          "Botswana" => "Botswana",
          "Brazilië" => "Brazilië",
          "Brunei" => "Brunei",
          "Bulgarije" => "Bulgarije",
          "Burkina Faso" => "Burkina Faso",
          "Burundi" => "Burundi",
          "Ivoorkust" => "Ivoorkust",
          "Cabo Verde" => "Cabo Verde",
          "Cambodja" => "Cambodja",
          "Kameroen" => "Kameroen",
          "Canada" => "Canada",
          "Centraal-Afrikaanse Republiek" => "Centraal-Afrikaanse Republiek",
          "Tsjaad" => "Tsjaad",
          "Chili" => "Chili",
          "China" => "China",
          "Colombia" => "Colombia",
          "Comoren" => "Comoren",
          "Congo (Congo-Brazzaville)" => "Congo (Congo-Brazzaville)",
          "Costa Rica" => "Costa Rica",
          "Kroatië" => "Kroatië",
          "Cuba" => "Cuba",
          "Cyprus" => "Cyprus",
          "Tsjechië (Tsjechische Republiek)" => "Tsjechië (Tsjechische Republiek)",
          "Democratische Republiek Congo" => "Democratische Republiek Congo",
          "Denemarken" => "Denemarken",
          "Djibouti" => "Djibouti",
          "Dominica" => "Dominica",
          "Dominikaanse Republiek" => "Dominikaanse Republiek",
          "Ecuador" => "Ecuador",
          "Egypte" => "Egypte",
          "El Salvador" => "El Salvador",
          "Equatoriaal-Guinea" => "Equatoriaal-Guinea",
          "Eritrea" => "Eritrea",
          "Estland" => "Estland",
          "Eswatini" => "Eswatini",
          "Ethiopië" => "Ethiopië",
          "Fiji" => "Fiji",
          "Finland" => "Finland",
          "Frankrijk" => "Frankrijk",
          "Gabon" => "Gabon",
          "Gambia" => "Gambia",
          "Georgië" => "Georgië",
          "Duitsland" => "Duitsland",
          "Ghana" => "Ghana",
          "Griekenland" => "Griekenland",
          "Grenada" => "Grenada",
          "Guatemala" => "Guatemala",
          "Guinee" => "Guinee",
          "Guinee-Bissau" => "Guinee-Bissau",
          "Guyana" => "Guyana",
          "Haïti" => "Haïti",
          "Heilige Stoel" => "Heilige Stoel",
          "Honduras" => "Honduras",
          "Hongarije" => "Hongarije",
          "IJsland" => "IJsland",
          "India" => "India",
          "Indonesië" => "Indonesië",
          "Iran" => "Iran",
          "Irak" => "Irak",
          "Ierland" => "Ierland",
          "Israël" => "Israël",
          "Italië" => "Italië",
          "Jamaica" => "Jamaica",
          "Japan" => "Japan",
          "Jordanië" => "Jordanië",
          "Kazachstan" => "Kazachstan",
          "Kenia" => "Kenia",
          "Kiribati" => "Kiribati",
          "Koeweit" => "Koeweit",
          "Kyrgyzstan" => "Kyrgyzstan",
          "Laos" => "Laos",
          "Letland" => "Letland",
          "Libanon" => "Libanon",
          "Lesotho" => "Lesotho",
          "Liberia" => "Liberia",
          "Libië" => "Libië",
          "Liechtenstein" => "Liechtenstein",
          "Litouwen" => "Litouwen",
          "Luxemburg" => "Luxemburg",
          "Madagaskar" => "Madagaskar",
          "Malawi" => "Malawi",
          "Maleisië" => "Maleisië",
          "Maldiven" => "Maldiven",
          "Mali" => "Mali",
          "Malta" => "Malta",
          "Marshalleilanden" => "Marshalleilanden",
          "Mauritanië" => "Mauritanië",
          "Mauritius" => "Mauritius",
          "Mexico" => "Mexico",
          "Micronesië" => "Micronesië",
          "Moldavië" => "Moldavië",
          "Monaco" => "Monaco",
          "Mongolië" => "Mongolië",
          "Montenegro" => "Montenegro",
          "Marokko" => "Marokko",
          "Mozambique" => "Mozambique",
          "Myanmar" => "Myanmar",
          "Namibië" => "Namibië",
          "Nauru" => "Nauru",
          "Nepal" => "Nepal",
          "Nederland" => "Nederland",
          "Nieuw-Zeeland" => "Nieuw-Zeeland",
          "Nicaragua" => "Nicaragua",
          "Niger" => "Niger",
          "Nigeria" => "Nigeria",
          "Noord-Korea" => "Noord-Korea",
          "Noord-Macedonië" => "Noord-Macedonië",
          "Noorwegen" => "Noorwegen",
          "Oman" => "Oman",
          "Pakistan" => "Pakistan",
          "Palau" => "Palau",
          "Palestijnse Staat" => "Palestijnse Staat",
          "Panama" => "Panama",
          "Papoea-Nieuw-Guinea" => "Papoea-Nieuw-Guinea",
          "Paraguay" => "Paraguay",
          "Peru" => "Peru",
          "Filipijnen" => "Filipijnen",
          "Polen" => "Polen",
          "Portugal" => "Portugal",
          "Qatar" => "Qatar",
          "Roemenië" => "Roemenië",
          "Rusland" => "Rusland",
          "Rwanda" => "Rwanda",
          "Saint Kitts en Nevis" => "Saint Kitts en Nevis",
          "Saint Lucia" => "Saint Lucia",
          "Saint Vincent en de Grenadines" => "Saint Vincent en de Grenadines",
          "Samoa" => "Samoa",
          "San Marino" => "San Marino",
          "Sao Tomé en Principe" => "Sao Tomé en Principe",
          "Saoedi-Arabië" => "Saoedi-Arabië",
          "Senegal" => "Senegal",
          "Servië" => "Servië",
          "Seychellen" => "Seychellen",
          "Sierra Leone" => "Sierra Leone",
          "Singapore" => "Singapore",
          "Slowakije" => "Slowakije",
          "Slovenië" => "Slovenië",
          "Salomonseilanden" => "Salomonseilanden",
          "Somalië" => "Somalië",
          "Zuid-Afrika" => "Zuid-Afrika",
          "Zuid-Korea" => "Zuid-Korea",
          "Zuid-Soedan" => "Zuid-Soedan",
          "Spanje" => "Spanje",
          "Sri Lanka" => "Sri Lanka",
          "Soedan" => "Soedan",
          "Suriname" => "Suriname",
          "Zweden" => "Zweden",
          "Zwitserland" => "Zwitserland",
          "Syrië" => "Syrië",
          "Tadzjikistan" => "Tadzjikistan",
          "Tanzania" => "Tanzania",
          "Thailand" => "Thailand",
          "Oost-Timor" => "Oost-Timor",
          "Togo" => "Togo",
          "Tonga" => "Tonga",
          "Trinidad en Tobago" => "Trinidad en Tobago",
          "Tunesië" => "Tunesië",
          "Turkije" => "Turkije",
          "Turkmenistan" => "Turkmenistan",
          "Tuvalu" => "Tuvalu",
          "Oeganda" => "Oeganda",
          "Oekraïne" => "Oekraïne",
          "Verenigde Arabische Emiraten" => "Verenigde Arabische Emiraten",
          "Verenigd Koninkrijk" => "Verenigd Koninkrijk",
          "Verenigde Staten van Amerika" => "Verenigde Staten van Amerika",
          "Uruguay" => "Uruguay",
          "Oezbekistan" => "Oezbekistan",
          "Vanuatu" => "Vanuatu",
          "Venezuela" => "Venezuela",
          "Vietnam" => "Vietnam",
          "Jemen" => "Jemen",
          "Zambia" => "Zambia",
          "Zimbabwe" => "Zimbabwe",
        ],
        'it' => [
            "Afghanistan" => "Afghanistan",
              "Albania" => "Albania",
              "Algeria" => "Algeria",
              "Andorra" => "Andorra",
              "Angola" => "Angola",
              "Antigua e Barbuda" => "Antigua e Barbuda",
              "Argentina" => "Argentina",
              "Armenia" => "Armenia",
              "Australia" => "Australia",
              "Austria" => "Austria",
              "Azerbaijan" => "Azerbaijan",
              "Bahamas" => "Bahamas",
              "Bahrain" => "Bahrain",
              "Bangladesh" => "Bangladesh",
              "Barbados" => "Barbados",
              "Bielorussia" => "Bielorussia",
              "Belgio" => "Belgio",
              "Belize" => "Belize",
              "Benin" => "Benin",
              "Bhutan" => "Bhutan",
              "Bolivia" => "Bolivia",
              "Bosnia ed Erzegovina" => "Bosnia ed Erzegovina",
              "Botswana" => "Botswana",
              "Brasile" => "Brasile",
              "Brunei" => "Brunei",
              "Bulgaria" => "Bulgaria",
              "Burkina Faso" => "Burkina Faso",
              "Burundi" => "Burundi",
              "Costa d'Avorio" => "Costa d'Avorio",
              "Cabo Verde" => "Cabo Verde",
              "Cambogia" => "Cambogia",
              "Camerun" => "Camerun",
              "Canada" => "Canada",
              "Repubblica Centrafricana" => "Repubblica Centrafricana",
              "Ciad" => "Ciad",
              "Cile" => "Cile",
              "Cina" => "Cina",
              "Colombia" => "Colombia",
              "Comore" => "Comore",
              "Congo (Congo-Brazzaville)" => "Congo (Congo-Brazzaville)",
              "Costa Rica" => "Costa Rica",
              "Croazia" => "Croazia",
              "Cuba" => "Cuba",
              "Cipro" => "Cipro",
              "Cechia (Repubblica Ceca)" => "Cechia (Repubblica Ceca)",
              "Repubblica Democratica del Congo" => "Repubblica Democratica del Congo",
              "Danimarca" => "Danimarca",
              "Gibuti" => "Gibuti",
              "Dominica" => "Dominica",
              "Repubblica Dominicana" => "Repubblica Dominicana",
              "Ecuador" => "Ecuador",
              "Egitto" => "Egitto",
              "El Salvador" => "El Salvador",
              "Guinea Equatoriale" => "Guinea Equatoriale",
              "Eritrea" => "Eritrea",
              "Estonia" => "Estonia",
              "Eswatini" => "Eswatini",
              "Etiopia" => "Etiopia",
              "Fiji" => "Fiji",
              "Finlandia" => "Finlandia",
              "Francia" => "Francia",
              "Gabon" => "Gabon",
              "Gambia" => "Gambia",
              "Georgia" => "Georgia",
              "Germania" => "Germania",
              "Ghana" => "Ghana",
              "Grecia" => "Grecia",
              "Grenada" => "Grenada",
              "Guatemala" => "Guatemala",
              "Guinea" => "Guinea",
              "Guinea-Bissau" => "Guinea-Bissau",
              "Guyana" => "Guyana",
              "Haiti" => "Haiti",
              "Santa Sede" => "Santa Sede",
              "Honduras" => "Honduras",
              "Ungheria" => "Ungheria",
              "Islanda" => "Islanda",
              "India" => "India",
              "Indonesia" => "Indonesia",
              "Iran" => "Iran",
              "Iraq" => "Iraq",
              "Irlanda" => "Irlanda",
              "Israele" => "Israele",
              "Italia" => "Italia",
              "Giamaica" => "Giamaica",
              "Giappone" => "Giappone",
              "Giordania" => "Giordania",
              "Kazakistan" => "Kazakistan",
              "Kenya" => "Kenya",
              "Kiribati" => "Kiribati",
              "Kuwait" => "Kuwait",
              "Kirghizistan" => "Kirghizistan",
              "Laos" => "Laos",
              "Lettonia" => "Lettonia",
              "Libano" => "Libano",
              "Lesotho" => "Lesotho",
              "Liberia" => "Liberia",
              "Libia" => "Libia",
              "Liechtenstein" => "Liechtenstein",
              "Lituania" => "Lituania",
              "Lussemburgo" => "Lussemburgo",
              "Madagascar" => "Madagascar",
              "Malawi" => "Malawi",
              "Malesia" => "Malesia",
              "Maldive" => "Maldive",
              "Mali" => "Mali",
              "Malta" => "Malta",
              "Isole Marshall" => "Isole Marshall",
              "Mauritania" => "Mauritania",
              "Mauritius" => "Mauritius",
              "Messico" => "Messico",
              "Micronesia" => "Micronesia",
              "Moldova" => "Moldova",
              "Monaco" => "Monaco",
              "Mongolia" => "Mongolia",
              "Montenegro" => "Montenegro",
              "Marocco" => "Marocco",
              "Mozambico" => "Mozambico",
              "Myanmar" => "Myanmar",
              "Namibia" => "Namibia",
              "Nauru" => "Nauru",
              "Nepal" => "Nepal",
              "Paesi Bassi" => "Paesi Bassi",
              "Nuova Zelanda" => "Nuova Zelanda",
              "Nicaragua" => "Nicaragua",
              "Niger" => "Niger",
              "Nigeria" => "Nigeria",
              "Corea del Nord" => "Corea del Nord",
              "Macedonia del Nord" => "Macedonia del Nord",
              "Norvegia" => "Norvegia",
              "Oman" => "Oman",
              "Pakistan" => "Pakistan",
              "Palau" => "Palau",
              "Stato della Palestina" => "Stato della Palestina",
              "Panama" => "Panama",
              "Papua Nuova Guinea" => "Papua Nuova Guinea",
              "Paraguay" => "Paraguay",
              "Perù" => "Perù",
              "Filippine" => "Filippine",
              "Polonia" => "Polonia",
              "Portogallo" => "Portogallo",
              "Qatar" => "Qatar",
              "Romania" => "Romania",
              "Russia" => "Russia",
              "Ruanda" => "Ruanda",
              "Saint Kitts e Nevis" => "Saint Kitts e Nevis",
              "Santa Lucia" => "Santa Lucia",
              "Saint Vincent e Grenadine" => "Saint Vincent e Grenadine",
              "Samoa" => "Samoa",
              "San Marino" => "San Marino",
              "Sao Tome e Principe" => "Sao Tome e Principe",
              "Arabia Saudita" => "Arabia Saudita",
              "Senegal" => "Senegal",
              "Serbia" => "Serbia",
              "Seychelles" => "Seychelles",
              "Sierra Leone" => "Sierra Leone",
              "Singapore" => "Singapore",
              "Slovacchia" => "Slovacchia",
              "Slovenia" => "Slovenia",
              "Isole Salomone" => "Isole Salomone",
              "Somalia" => "Somalia",
              "Sudafrica" => "Sudafrica",
              "Corea del Sud" => "Corea del Sud",
              "Sudan del Sud" => "Sudan del Sud",
              "Spagna" => "Spagna",
              "Sri Lanka" => "Sri Lanka",
              "Sudan" => "Sudan",
              "Suriname" => "Suriname",
              "Svezia" => "Svezia",
              "Svizzera" => "Svizzera",
              "Siria" => "Siria",
              "Tajikistan" => "Tajikistan",
              "Tanzania" => "Tanzania",
              "Thailandia" => "Thailandia",
              "Timor-Leste" => "Timor-Leste",
              "Togo" => "Togo",
              "Tonga" => "Tonga",
              "Trinidad e Tobago" => "Trinidad e Tobago",
              "Tunisia" => "Tunisia",
              "Turchia" => "Turchia",
              "Turkmenistan" => "Turkmenistan",
              "Tuvalu" => "Tuvalu",
              "Uganda" => "Uganda",
              "Ucraina" => "Ucraina",
              "Emirati Arabi Uniti" => "Emirati Arabi Uniti",
              "Regno Unito" => "Regno Unito",
              "Stati Uniti d'America" => "Stati Uniti d'America",
              "Uruguay" => "Uruguay",
              "Uzbekistan" => "Uzbekistan",
              "Vanuatu" => "Vanuatu",
              "Venezuela" => "Venezuela",
              "Vietnam" => "Vietnam",
              "Yemen" => "Yemen",
              "Zambia" => "Zambia",
              "Zimbabwe" => "Zimbabwe",
        ],
        'pl' => [
            "Afganistan" => "Afganistan",
              "Albania" => "Albania",
              "Algieria" => "Algieria",
              "Andora" => "Andora",
              "Angola" => "Angola",
              "Antigua i Barbuda" => "Antigua i Barbuda",
              "Argentyna" => "Argentyna",
              "Armenia" => "Armenia",
              "Australia" => "Australia",
              "Austria" => "Austria",
              "Azerbejdżan" => "Azerbejdżan",
              "Bahamy" => "Bahamy",
              "Bahrajn" => "Bahrajn",
              "Bangladesz" => "Bangladesz",
              "Barbados" => "Barbados",
              "Białoruś" => "Białoruś",
              "Belgia" => "Belgia",
              "Belize" => "Belize",
              "Benin" => "Benin",
              "Bhutan" => "Bhutan",
              "Boliwia" => "Boliwia",
              "Bośnia i Hercegowina" => "Bośnia i Hercegowina",
              "Botswana" => "Botswana",
              "Brazylia" => "Brazylia",
              "Brunei" => "Brunei",
              "Bułgaria" => "Bułgaria",
              "Burkina Faso" => "Burkina Faso",
              "Burundi" => "Burundi",
              "Wybrzeże Kości Słoniowej" => "Wybrzeże Kości Słoniowej",
              "Cabo Verde" => "Cabo Verde",
              "Kambodża" => "Kambodża",
              "Kamerun" => "Kamerun",
              "Kanada" => "Kanada",
              "Republika Środkowoafrykańska" => "Republika Środkowoafrykańska",
              "Czad" => "Czad",
              "Chile" => "Chile",
              "Chiny" => "Chiny",
              "Kolumbia" => "Kolumbia",
              "Komory" => "Komory",
              "Kongo (Kongo-Brazzaville)" => "Kongo (Kongo-Brazzaville)",
              "Kostaryka" => "Kostaryka",
              "Chorwacja" => "Chorwacja",
              "Kuba" => "Kuba",
              "Cypr" => "Cypr",
              "Czechia (Republika Czeska)" => "Czechia (Republika Czeska)",
              "Demokratyczna Republika Konga" => "Demokratyczna Republika Konga",
              "Dania" => "Dania",
              "Dżibuti" => "Dżibuti",
              "Dominika (Dominica)" => "Dominika (Dominica)",
              "Republika Dominikańska" => "Republika Dominikańska",
              "Ekwador" => "Ekwador",
              "Egipt" => "Egipt",
              "Salwador" => "Salwador",
              "Gwinea Równikowa" => "Gwinea Równikowa",
              "Erytrea" => "Erytrea",
              "Estonia" => "Estonia",
              "Eswatini" => "Eswatini",
              "Etiopia" => "Etiopia",
              "Fidżi" => "Fidżi",
              "Finlandia" => "Finlandia",
              "Francja" => "Francja",
              "Gabon" => "Gabon",
              "Gambia" => "Gambia",
              "Gruzja" => "Gruzja",
              "Niemcy" => "Niemcy",
              "Ghana" => "Ghana",
              "Grecja" => "Grecja",
              "Grenada" => "Grenada",
              "Gwatemala" => "Gwatemala",
              "Gwinea" => "Gwinea",
              "Gwinea Bissau" => "Gwinea Bissau",
              "Gujana" => "Gujana",
              "Haiti" => "Haiti",
              "Stolica Apostolska" => "Stolica Apostolska",
              "Honduras" => "Honduras",
              "Węgry" => "Węgry",
              "Islandia" => "Islandia",
              "Indie" => "Indie",
              "Indonezja" => "Indonezja",
              "Iran" => "Iran",
              "Irak" => "Irak",
              "Irlandia" => "Irlandia",
              "Izrael" => "Izrael",
              "Włochy" => "Włochy",
              "Jamajka" => "Jamajka",
              "Japonia" => "Japonia",
              "Jordania" => "Jordania",
              "Kazachstan" => "Kazachstan",
              "Kenia" => "Kenia",
              "Kiribati" => "Kiribati",
              "Kuwejt" => "Kuwejt",
              "Kirgistan" => "Kirgistan",
              "Laos" => "Laos",
              "Łotwa" => "Łotwa",
              "Liban" => "Liban",
              "Lesotho" => "Lesotho",
              "Liberia" => "Liberia",
              "Libia" => "Libia",
              "Liechtenstein" => "Liechtenstein",
              "Litwa" => "Litwa",
              "Luksemburg" => "Luksemburg",
              "Madagaskar" => "Madagaskar",
              "Malawi" => "Malawi",
              "Malezja" => "Malezja",
              "Malediwy" => "Malediwy",
              "Mali" => "Mali",
              "Malta" => "Malta",
              "Wyspy Marshalla" => "Wyspy Marshalla",
              "Mauretania" => "Mauretania",
              "Mauritius" => "Mauritius",
              "Meksyk" => "Meksyk",
              "Mikronezja" => "Mikronezja",
              "Mołdawia" => "Mołdawia",
              "Monako" => "Monako",
              "Mongolia" => "Mongolia",
              "Czarnogóra" => "Czarnogóra",
              "Maroko" => "Maroko",
              "Mozambik" => "Mozambik",
              "Myanmar" => "Myanmar",
              "Namibia" => "Namibia",
              "Nauru" => "Nauru",
              "Nepal" => "Nepal",
              "Niderlandy" => "Niderlandy",
              "Nowa Zelandia" => "Nowa Zelandia",
              "Nikaragua" => "Nikaragua",
              "Niger" => "Niger",
              "Nigeria" => "Nigeria",
              "Korea Północna" => "Korea Północna",
              "Macedonia Północna" => "Macedonia Północna",
              "Norwegia" => "Norwegia",
              "Oman" => "Oman",
              "Pakistan" => "Pakistan",
              "Palau" => "Palau",
              "Państwo Palestyna" => "Państwo Palestyna",
              "Panama" => "Panama",
              "Papua Nowa Gwinea" => "Papua Nowa Gwinea",
              "Paragwaj" => "Paragwaj",
              "Peru" => "Peru",
              "Filipiny" => "Filipiny",
              "Polska" => "Polska",
              "Portugalia" => "Portugalia",
              "Katar" => "Katar",
              "Rumunia" => "Rumunia",
              "Rosja" => "Rosja",
              "Rwanda" => "Rwanda",
              "Saint Kitts i Nevis" => "Saint Kitts i Nevis",
              "Saint Lucia" => "Saint Lucia",
              "Saint Vincent i Grenadyny" => "Saint Vincent i Grenadyny",
              "Samoa" => "Samoa",
              "San Marino" => "San Marino",
              "Wyspy Świętego Tomasza i Książęca" => "Wyspy Świętego Tomasza i Książęca",
              "Arabia Saudyjska" => "Arabia Saudyjska",
              "Senegal" => "Senegal",
              "Serbia" => "Serbia",
              "Seszele" => "Seszele",
              "Sierra Leone" => "Sierra Leone",
              "Singapur" => "Singapur",
              "Słowacja" => "Słowacja",
              "Słowenia" => "Słowenia",
              "Wyspy Salomona" => "Wyspy Salomona",
              "Somalia" => "Somalia",
              "Republika Południowej Afryki" => "Republika Południowej Afryki",
              "Korea Południowa" => "Korea Południowa",
              "Sudan Południowy" => "Sudan Południowy",
              "Hiszpania" => "Hiszpania",
              "Sri Lanka" => "Sri Lanka",
              "Sudan" => "Sudan",
              "Surinam" => "Surinam",
              "Szwecja" => "Szwecja",
              "Szwajcaria" => "Szwajcaria",
              "Syria" => "Syria",
              "Tadżykistan" => "Tadżykistan",
              "Tanzania" => "Tanzania",
              "Tajlandia" => "Tajlandia",
              "Timor Wschodni" => "Timor Wschodni",
              "Togo" => "Togo",
              "Tonga" => "Tonga",
              "Trynidad i Tobago" => "Trynidad i Tobago",
              "Tunezja" => "Tunezja",
              "Turcja" => "Turcja",
              "Turkmenistan" => "Turkmenistan",
              "Tuvalu" => "Tuvalu",
              "Uganda" => "Uganda",
              "Ukraina" => "Ukraina",
              "Zjednoczone Emiraty Arabskie" => "Zjednoczone Emiraty Arabskie",
              "Zjednoczone Królestwo" => "Zjednoczone Królestwo",
              "Stany Zjednoczone Ameryki" => "Stany Zjednoczone Ameryki",
              "Urugwaj" => "Urugwaj",
              "Uzbekistan" => "Uzbekistan",
              "Vanuatu" => "Vanuatu",
              "Wenezuela" => "Wenezuela",
              "Wietnam" => "Wietnam",
              "Jemen" => "Jemen",
              "Zambia" => "Zambia",
              "Zimbabwe" => "Zimbabwe",
        ]
    ],

    /**
     * Debug / testing
     */
    'force-enable-all-modules' => false,
];
